language: c
os: linux
dist: focal

# Blacklist
branches:
  only:
    - master

services:
    - docker

compiler:
    - gcc

before_install:
    - echo "deb http://ppa.launchpad.net/snaipewastaken/ppa/ubuntu cosmic main" | sudo tee -a ${TRAVIS_ROOT}/etc/apt/sources.list >/dev/null
    - sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com CE6500E9003E6E24
    - sudo apt-get -q update
    - sudo apt-get -y install pkg-config doxygen openssl zlib1g-dev build-essential criterion-dev gcovr graphviz


stages:
    -name: criterion
    if: branch = master
    -name: autobahn
    if: branch = master
    -name: documentation
    if: branch = master
    -name: deploy
    if: branch = master

jobs:
    include:
        -stage: criterion 
        name: "Criterion Unit Tests"
        script: make test
        -stage: autobahn
        name: "Unit and performance Tests"
        script: make autobahn
        -stage: documentation
        name: "HTML Documentation of source code"
        script: make docs
        -stage: deploy
        deploy:
          strategy: git
          provider: pages
          skip_cleanup: true
          local_dir: generated
          github_token: $GH_REPO_TOKEN
          on:
            branch: master
