language: C

# This will run on Travis' 'new' container-based infrastructure
sudo: false 

# Blacklist
branches:
  only:
    - master

services:
    - docker

# Install dependencies
addons:
  apt:
    sources:
      - sourceline: 'ppa:snaipewastaken/ppa'
    packages:
      - doxygen
      - openssl
      - zlib1g-dev
      - build-essential
      - criterion-dev

# Build your code e.g. by calling make
script:
  - make test
  - make docs
  - make autobahn

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
