language: c
os: linux
dist: focal

# Blacklist
branches:
  only:
    - master

services:
    - docker

compiler:
    - gcc

before_install:
    - sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com CE6500E9003E6E24

# Install dependencies
addons:
  apt:
    sources:
      - sourceline: 'deb http://ppa.launchpad.net/snaipewastaken/ppa/ubuntu cosmic main'
    packages:
      - pkg-config
      - doxygen
      - openssl
      - zlib1g-dev
      - build-essential
      - criterion-dev
      - gcovr
      - graphviz

# Build your code e.g. by calling make
script:
  - make test
  - make docs
  - make autobahn

# Generate and deploy documentation
deploy:
  strategy: git
  provider: pages
  skip_cleanup: true
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
