language: c
os: linux
dist: focal

# Blacklist
branches:
  only:
    - master

services:
    - docker

compiler:
    - gcc

before_install:
    - echo "deb http://ppa.launchpad.net/snaipewastaken/ppa/ubuntu cosmic main" | sudo tee -a ${TRAVIS_ROOT}/etc/apt/sources.list >/dev/null
    - sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com CE6500E9003E6E24
    - sudo apt-get -q update
    - sudo apt-get -y install pkg-config doxygen openssl zlib1g-dev build-essential criterion-dev gcovr graphviz

# Build your code e.g. by calling make
jobs:
    include:
        -stage: criterion 
        name: "Criterion Unit Tests"
        script: make test
        -stage: autobahn
        name: "Unit and performance Tests"
        script: make autobahn
        -stage: documentation
        name: "HTML Documentation of source code"
        script: make docs

stages:
    -criterion
    -autobahn
    -documentation

# Generate and deploy documentation
deploy:
  strategy: git
  provider: pages
  skip_cleanup: true
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
